user:
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
  phone_number_min_length: 10
  address_max_length: 200
course:
  title_max_length: 250
  description_max_length: 400
subject:
  title_max_length: 250
  description_max_length: 400
sessions:
  check_session: "1"
user_per_page: 10
subjects_per_page: 10
courses_per_page: 10
